Airforce.Web/Controllers/AirbaseController.cs
using Microsoft.AspNetCore.Mvc;
using Alesik.Haidov.Airforce.Web.Services;
using Alesik.Haidov.Airforce.Web.Models;
using Alesik.Haidov.Airforce.Web.Models;
using Alesik.Haidov.Airforce.Web.Services;


namespace Alesik.Haidov.Airforce.Web.Controllers
{
    public class AirbaseController : Controller
    {
        private readonly AirbaseService _airbaseService;

        public AirbaseController(AirbaseService airbaseService)
        {
            _airbaseService = airbaseService;
        }

        public IActionResult Index()
        {
            var airbases = _airbaseService.GetAllAirbases();
            return View(airbases);
        }

        public IActionResult Details(string id)
        {
            var airbase = _airbaseService.GetAirbaseById(id);
            if (airbase == null)
            {
                return NotFound();
            }
            return View(airbase);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Airbase airbase)
        {
            if (!string.IsNullOrWhiteSpace(airbase.Name) & !string.IsNullOrWhiteSpace(airbase.Location))
            {
                _airbaseService.CreateOrUpdateAirbase(airbase);
                return RedirectToAction(nameof(Index));
            }
            return View(airbase);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var airbase = _airbaseService.GetAirbaseById(id);
            if (airbase == null)
            {
                return NotFound();
            }
            return View(airbase);
        }

        [HttpPost]
        public IActionResult Edit(Airbase airbase)
        {
            if (!ModelState.IsValid)
            {
                return View(airbase);
            }

            _airbaseService.CreateOrUpdateAirbase(airbase);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(string id)
        {
            var airbase = _airbaseService.GetAirbaseById(id);
            if (airbase == null)
            {
                return NotFound();
            }
            return View(airbase);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            var aircraft = _airbaseService.GetAirbaseById(id);
            if (aircraft != null)
            {
                _airbaseService.RemoveAirbase(aircraft.GUID);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Airforce.Web/Controllers/AircraftController.cs
using Microsoft.AspNetCore.Mvc;
using Alesik.Haidov.Airforce.Web.Services;
using Alesik.Haidov.Airforce.Web.Models;
using Alesik.Haidov.Airforce.Core;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Alesik.Haidov.Airforce.Web.Controllers
{
    public class AircraftController : Controller
    {
        private readonly AircraftService _aircraftService;
        private readonly AirbaseService _airbaseService;

        public AircraftController(AircraftService aircraftService, AirbaseService airbaseService)
        {
            _aircraftService = aircraftService;
            _airbaseService = airbaseService;
        }

        public IActionResult Index()
        {
            var aircrafts = _aircraftService.GetAllAircrafts();
            return View(aircrafts);
        }

        public IActionResult Details(string id)
        {
            var aircraft = _aircraftService.GetAircraftById(id);
            if (aircraft == null)
            {
                return NotFound();
            }
            return View(aircraft);
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Assuming your airbase service method returns a list of airbases
            var airbases = _airbaseService.GetAllAirbases();

            ViewData["Types"] = Enum.GetValues(typeof(AircraftType));
            ViewBag.Airbases = new SelectList(_airbaseService.GetAllAirbases(), "GUID", "Name");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Aircraft aircraft)
        {
            if (aircraft != null)
            {
                if (!string.IsNullOrEmpty(aircraft.AirbaseGUID))
                {
                    aircraft.Airbase = _airbaseService.GetAirbaseById(aircraft.AirbaseGUID);
                }

                _aircraftService.CreateOrUpdateAircraft(aircraft);
                return RedirectToAction(nameof(Index));
            }
            return View(aircraft);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var aircraft = _aircraftService.GetAircraftById(id);
            if (aircraft == null)
            {
                return NotFound();
            }

            aircraft.AirbaseGUID = aircraft.Airbase?.GUID;

            ViewData["Types"] = Enum.GetValues(typeof(AircraftType));
            ViewBag.Airbases = new SelectList(_airbaseService.GetAllAirbases(), "GUID", "Name");

            return View(aircraft);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Aircraft aircraft)
        {
            if (aircraft != null)
            {
                if (!string.IsNullOrEmpty(aircraft.AirbaseGUID))
                {
                    aircraft.Airbase = _airbaseService.GetAirbaseById(aircraft.AirbaseGUID);
                }

                _aircraftService.CreateOrUpdateAircraft(aircraft);
                return RedirectToAction(nameof(Index));
            }
            return View(aircraft);
        }




        public IActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var aircraft = _aircraftService.GetAircraftById(id);
            if (aircraft == null)
            {
                return NotFound();
            }

            return View(aircraft);
        }

        // POST: Aircraft/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            var aircraft = _aircraftService.GetAircraftById(id);
            if (aircraft != null)
            {
                _aircraftService.RemoveAircraft(aircraft.GUID);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Airforce.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Airforce.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Airforce.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Aircraft" asp-action="Index">Airforce.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Aircraft" asp-action="Index">Aircraft</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Airbase" asp-action="Index">Airbase</a>
                        </li>
                        <!-- Add other navigation links here -->
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Airforce.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>